# Generated by Django 4.2.5 on 2023-10-24 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='admin',
        ),
        migrations.AddField(
            model_name='entidad',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunicador',
            name='entidad',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.entidad'),
        ),
    ]
